### ISSUE TITLE
# 1146 - The table 'id16202014_shoot.config' does not exist

### ISSUE THREAD

**Issue by kamalzariah** [creativecoder/piwik-heroku#13]
I get this issue when I upload the database to PHPMyAdmin

...

[content removed, as it seemed to be a database dump with private information]

**Comment by creativecoder** [comment]
Hi there, it seems that database dump in the issue description was leaking private information, so I've removed it. It also seemed to be unrelated to this project, so I'm closing the issue.

If you have an issue to report related to this project, feel free to re-open and update the description with the relevant details.
