### ISSUE TITLE
dokku instruction

### ISSUE THREAD

**Issue by fi0** [creativecoder/piwik-heroku#5]
is dokku deployment supported? and how?

**Comment by creativecoder** [comment]
Nothing special needed for running on dokku, follow the instructions in the readme (provision a dokku app, add a mariadb/mysql resource, etc). I run this on a dokku instance, myself.

There does seem to be an issue with database tables when first installing that I haven't resolved yet, but that's not unique to dokku... workaround is https://github.com/creativecoder/piwik-heroku/issues/2#issuecomment-433445174
